name: CI (Linux/Ubuntu)

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # note that we need static libs (in Ubuntu, *-dev)
    - name: install required libraries
      run: apt install libflint-dev liblapack3-dev z3
    - name: install project dependencies
      run: stack --no-terminal test --only-dependencies
    - name: build and run tests
      run: stack --no-terminal haddock --test --no-haddock-deps
